const arrayDatadeBasedeDatos = [
    {
        id: 1,
        nombre: "Isabel viendo llover en Macondo",        
        autor: "Gabriel Garcia Marquez",
        editorial: "Estuario",
        añoEdicion: 1977,
        genero: "Realismo mágico",
        descripcion: "Una lluvia que parece no tener final cae un domingo en Macondo y de la voz de Isabel nos enteramos de la destrucción que dejará en el pueblo, pero también de la distorsión de la realidad que la constancia de las gotas ha creado en la mente de los personajes.",
        precio: 3500,
        stock: 7,
        tapa: "https://cloud10.todocoleccion.online/libros-segunda-mano-cuentos/tc/2018/05/12/12/120720947.webp",
    },
    {
        id: 2,
        nombre: "La borra y el cafe" ,
        autor: "Mario Benedeti",
        editorial: "Planeta S.A.",
        añoEdicion: 1992,
        genero: "Novela",
        descripcion: "Novela inolvidable, donde el humor y el amor a los seres humanos se convierte en reflejo de nosotros mismos. La borra del café consta de cuarenta y ocho fragmentos y un enigma desarrollado en la imagen misteriosa de una mujer, la presencia de una higuera y la reiteración a lo largo de los años de una hora, las tres y diez. Benedetti rescata, en un espacio de ensueño, las anécdotas que acompañaron a Claudio, el protagonista, durante su niñez en Montevideo.",
        precio: 4500,
        stock: 20,
        tapa: "https://img1.od-cdn.com/ImageType-400/2335-1/810/95F/01/%7B81095F01-8177-4931-A44D-9E31B8AB8E76%7DImg400.jpg",
    },
    {
        id: 3,
        nombre: "El hechizo del agua",
        autor: "Florencia Bonelli",
        editorial: "Planeta S.A.",
        añoEdicion: 2022,
        genero: "Novela literaria",
        descripcion: "Brenda Gómez tiene una vida perfecta. Es una alumna destacada en la carrera de Ciencias Económicas, su novio es un joven ambicioso y con un gran futuro, sus amigas son leales, su familia la adora. Pero ella no es feliz.",
        precio: 850,
        stock: 10,
        tapa: "https://contentv2.tap-commerce.com/cover/large/9789504975847_1.jpg?id_com=1113",
    },
    {
        id: 4,
        nombre: "El arte de amar",
        autor: "Erich From",
        editorial: "PlanetaLector", 
        añoEdicion: 1956,
        genero: "Novela",
        descripcion: "«El amor intenta entender, convencer, vivificar. Por este motivo, el que ama se transforma constantemente. Capta más, observa más, es más productivo, es más él mismo.» El arte de amar es uno de los títulos clave en la bibliografía de Erich Fromm. En él, el filósofo alemán no pretende un manual ni una guía. Fromm considera el amor no como una sensación placentera de autosatisfacción sino como un arte hacia los demás que requiere un conocimiento y un esfuerzo.",
        precio: 1700,
        stock: 12,
        tapa: "https://images.cdn3.buscalibre.com/fit-in/360x360/cc/eb/ccebc8ca7534225899590754dc41ea00.jpg",
    },
    {
        id: 5,
        nombre: "Don Quijote de la mancha",
        autor: "Miguel de Cervantes",
        editorial: "Imprenta Juan de la Cuesta", 
        añoEdicion: 1605,
        genero: "Novela chistosa",
        descripcion: "Don Quijote de la Mancha se ha erigido en un clásico de la literatura universal y, al mismo tiempo, en el antecedente directo de la gran novela contemporánea. Con la primera parte, el autor parodió los libros de caballerías, gastados y anacrónicos, con la creación de un personaje genial, don Quijote, y su escudero, Sancho Panza. La segunda parte, en cambio, dota a la novela de una de sus principales características modernas: la importancia de la psicología del personaje para mover los hilos de la acción.",
        precio: 1000,
        stock: 16,
        tapa: "https://www.elejandria.com/covers/Don_Quijote_de_la_Mancha-Cervantes_Miguel-lg.png",
    },
    {
        id: 6,
        nombre: "La vida es un sueño", 
        autor: "Pedro Calderón de la Barca", 
        editorial: "Nula", 
        añoEdicion: 1635,
        genero: "Drama",
        descripcion: "La vida es sueño es una obra de teatro de Pedro Calderón de la Barca estrenada en 1635 y perteneciente al movimiento literario del barroco. El tema central es la libertad del ser humano para configurar su vida, sin dejarse llevar por un supuesto destino",
        precio: 3600,
        stock: 10,
        tapa: "https://novamosadormirnunca.files.wordpress.com/2016/10/90787-libro-la-vida-es-un-sueno-calderon-de-la-barca_mla-f-3054679792_082012.jpg",
    },
    {
        id: 7,
        nombre: "1984", 
        autor: "George Orwell", 
        editorial: "Zig-Zag",
        descripcion: "1984 es una de las novelas más inquietantes y atractivas del siglo XX. En el año 1984 Londres es una ciudad lúgubre en la que la Policía del Pensamiento controla de forma asfixiante la vida de los ciudadanos. Winston Smith es un peón de este engranaje perverso, su cometido es reescribir la historia para adaptarla a lo que el Partido considera la versión oficial de los hechos... hasta que decide replantearse la verdad del sistema que los gobierna y somete.", 
        añoEdicion: 1956,
        genero: "Ciencia Ficción",
        precio: 1500,
        stock: 5,
        tapa: "https://http2.mlstatic.com/D_NQ_NP_689164-MLA49288654765_032022-O.webp",
    },
    {
        id: 8,
        nombre: "El amor en tiempos de cólera", 
        autor: "Garcia Marquez", 
        editorial: "La oveja negra LTDA", 
        añoEdicion: 1985,
        genero: "Romántica",
        descripcion: "Dos historias hay en este libro. Una de ellas, apenas esbozada, es la de un amor secreto que culmina en la muerte elegida por un hombre que ha querido ponerse a salvo 'de los tormentos de la memoria'. La otra historia es la de un amor que hace de esos tormentos su alimento. Un amor acechado por los enemigos: el deterioro físico, la vejez, la muerte, pero que es capaz, no sólo de resistirlos, sino también de transformarlos en el ímpetu del deseo. Una muchacha de dieciocho años rechaza al hombre de quien ha estado enamorada y con quien le han impedido unirse.",
        precio: 4600,
        stock: 5,
        tapa: "https://trabalibros.com/rs/2036/4886d523-1977-4fa1-ab24-df1b609c897c/2c5/filename/el-amor-en-los-tiempos-del-colera-gabriel-garcia-marquez-trabalibros.jpg",
    },
    {
        id: 9,
        nombre: "De amor y de sombra", 
        autor: "Isabel Allende", 
        editorial: "De bolsillo, Colección", 
        añoEdicion: 2004,
        genero: "Romántica",
        descripcion: "Esta es la historia de una mujer y de un hombre que se amaron en plenitud, salvándose así de una existencia vulgar. 'La he llevado en la memoria cuidándola para que el tiempo no la desgaste, y es sólo ahora cuando puedo finalmente contarla. Lo haré por ellos y por otros que me confiaron sus vidas para que no las borre el viento...' Estas bellas palabras proporcionan la clave de un libro en el que la imaginación y realidad discurren al mismo nivel.",
        precio: 2000,
        stock: 15,
        tapa: "https://quelibroleo.com/images/libros/libro_1363643718.jpg",
    },
    {
        id: 10,
        nombre: "Noches blancas", 
        autor: "Green John, Johnson M., Myracle L.", 
        editorial: "La oveja negra LTDA", 
        añoEdicion: 1985,
        genero: "Romántica",
        descripcion: "Todo puede cambiar en cuestión de segundos, solo se necesita un poco de nieve y de magia navideña. La vida de Jubilee no es perfecta: acaba de discutir con su novio Noah y tiene que viajar hacia Florida por un problema con sus padres. Pero una inesperada tormenta de nieve en Nochebuena lo cambiará todo cuando el tren en el que viaja se detiene en la pequeña localidad de Gracetown. Afortunadamente, conoce a Stuart, un joven del mismo tren que la invita a pasar las fiestas con su familia. Como con las piezas de un dominó, un beso lo cambiará todo, y dará lugar a otras dos historias de amor.",
        precio: 1520,
        stock: 11,
        tapa: "https://http2.mlstatic.com/D_NQ_NP_654901-MLA20435808036_092015-O.webp",
    },
    {
        id: 11,
        nombre: "El Arte de Mirar", 
        autor: "Susan Woodford", 
        editorial: "Nube de tinta", 
        añoEdicion: 2018,
        genero: "Romántica",
        descripcion: "Ya sea ante una xilografía japonesa, La última Cena, de Leonardo da Vinci, o el Guernica, de Pablo Picasso, El arte de mirar le ayudará a afinar la vista y le dará mayor confianza a la hora de analizar imágenes. Esta guía esencial cuenta con un glosario de términos clave, que abarca desde movimientos artísticos y terminología técnica hasta léxico religioso y clásico, y una valiosa lista de lecturas recomendadas. Los que disfrutan del arte y quieren profundizar en él encontrarán en Esenciales del arte un acompañamiento perfecto que les proporcionará toda la información contextual necesaria para disfrutarlo y comprenderlo, tanto si se trata de un ávido galerista, un aficionado a leer cómodamente en el sillón o un curioso observador. Con textos atractivos, accesibles, acreditados, con un marcado componente visual y redactados y concebidos por expertos.",
        precio: 1100,
        stock: 13,
        tapa: "https://http2.mlstatic.com/D_NQ_NP_907911-MLA28141397668_092018-O.webp",
    },
    {
        id: 12,
        nombre: "El lenguaje del alma", 
        autor: "Josep Soler", 
        editorial: "Gaia Ediciones", 
        añoEdicion: 2015,
        genero: "Autoayuda",
        descripcion: "En El lenguaje del alma descubrirás que la respuesta es definitivamente SÍ: sí, la Vida es sabia; sí, todo lo que ocurre en la vida y en el cuerpo tiene sentido; y sí, hay alguien que siempre está ahí para nosotros, y ese alguien es nuestra alma. Tanto desde lo que percibimos como realidad externa (lo que parece estar ahí fuera) como desde nuestro interior, el alma nos envía sus mensajes en una miríada de formas, y para poder comprender lo que ella nos dice es preciso despertar un arte que hemos olvidado: el arte de escuchar la Vida.",
        precio: 1200,
        stock: 5,
        tapa: "https://http2.mlstatic.com/D_NQ_NP_783955-MLA46401685136_062021-O.webp",
    },
];

export default arrayDatadeBasedeDatos;