const arrayDatadeBasedeDatos = [
    {
        id: 1,
        nombre: "Isabel viendo llover en Macondo",
        autor: "Gabriel Garcia Marquez",
        editorial: "Estuario",
        añoEdicion: 1977,
        genero: "Realismo mágico",
        precio: 85,
        tapa: "https://cloud10.todocoleccion.online/libros-segunda-mano-cuentos/tc/2018/05/12/12/120720947.webp",
    },
    {
        id: 2,
        nombre: "La borra y el cafe" ,
        autor: "Mario Benedeti",
        editorial: "Planeta S.A.",
        añoEdicion: 1992,
        genero: "Novela",
        precio: 46,
        tapa: "https://img1.od-cdn.com/ImageType-400/2335-1/810/95F/01/%7B81095F01-8177-4931-A44D-9E31B8AB8E76%7DImg400.jpg",
    },
    {
        id: 3,
        nombre: "El hechizo del agua",
        autor: "Florencia Bonelli",
        editorial: "Planeta S.A.",
        añoEdicion: 2022,
        genero: "Novela literaria",
        precio: 75,
        tapa: "https://contentv2.tap-commerce.com/cover/large/9789504975847_1.jpg?id_com=1113",
    },
    {
        id: 4,
        nombre: "El arte de amar",
        autor: "Erich From",
        editorial: "PlanetaLector", 
        añoEdicion: 1956,
        genero: "Novela",
        precio: 46,
        tapa: "https://images.cdn3.buscalibre.com/fit-in/360x360/cc/eb/ccebc8ca7534225899590754dc41ea00.jpg",
    },
    {
        id: 5,
        nombre: "Don Quijote de la mancha",
        autor: "Miguel de Cervantes",
        editorial: "Imprenta Juan de la Cuesta", 
        añoEdicion: 1605,
        genero: "Novela chistosa",
        precio: 100,
        tapa: "https://www.elejandria.com/covers/Don_Quijote_de_la_Mancha-Cervantes_Miguel-lg.png",
    },
    {
        id: 6,
        nombre: "La vida es un sueño", 
        autor: "Pedro Calderón de la Barca", 
        editorial: "Nula", 
        añoEdicion: 1635,
        genero: "Drama",
        precio: 65,
        tapa: "https://novamosadormirnunca.files.wordpress.com/2016/10/90787-libro-la-vida-es-un-sueno-calderon-de-la-barca_mla-f-3054679792_082012.jpg",
    },
    {
        id: 7,
        nombre: "1984", 
        autor: "George Orwell", 
        editorial: "Zig-Zag", 
        añoEdicion: 1956,
        genero: "Ciencia Ficción",
        precio: 45,
        tapa: "https://http2.mlstatic.com/D_NQ_NP_689164-MLA49288654765_032022-O.webp",
    },
    {
        id: 8,
        nombre: "El amor en tiempos de cólera", 
        autor: "Garcia Marquez", 
        editorial: "La oveja negra LTDA", 
        añoEdicion: 1985,
        genero: "Romántica",
        precio: 46.5,
        tapa: "https://trabalibros.com/rs/2036/4886d523-1977-4fa1-ab24-df1b609c897c/2c5/filename/el-amor-en-los-tiempos-del-colera-gabriel-garcia-marquez-trabalibros.jpg",
    },
    {
        id: 9,
        nombre: "De amor y de sombra", 
        autor: "Isabel Allende", 
        editorial: "De bolsillo, Colección", 
        añoEdicion: 2004,
        genero: "Romántica",
        precio: 50,
        tapa: "https://quelibroleo.com/images/libros/libro_1363643718.jpg",
    },
    {
        id: 10,
        nombre: "Noche blanca", 
        autor: "Green John, Johnson M., Myracle L.", 
        editorial: "La oveja negra LTDA", 
        añoEdicion: 1985,
        genero: "Romántica",
        precio: 50,
        tapa: "https://http2.mlstatic.com/D_NQ_NP_654901-MLA20435808036_092015-O.webp",
    },
    {
        id: 11,
        nombre: "El Arte de Mirar", 
        autor: "Susan Woodford", 
        editorial: "Blume", 
        añoEdicion: 2018,
        genero: "Romántica",
        precio: 46,
        tapa: "https://http2.mlstatic.com/D_NQ_NP_907911-MLA28141397668_092018-O.webp",
    },
    {
        id: 12,
        nombre: "El lenguaje del alma", 
        autor: "Josep Soler", 
        editorial: "Gaia Ediciones", 
        añoEdicion: 2015,
        genero: "Autoayuda",
        precio: 50,
        tapa: "https://http2.mlstatic.com/D_NQ_NP_783955-MLA46401685136_062021-O.webp",
    },
];

export default arrayDatadeBasedeDatos;